//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oauth_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Cartings = new HashSet<Carting>();
        }
    
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string BIRTHDAY { get; set; }
        public string SEX { get; set; }
        public string EMAIL { get; set; }
        public string TELE { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual ICollection<Carting> Cartings { get; set; }
    }
}
