//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oauth_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carting
    {
        public string ACCOUNT { get; set; }
        public string PRODUCT { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public string IMG { get; set; }
        public string SIZE { get; set; }
        public Nullable<int> COST { get; set; }
        public string TIME { get; set; }
    
        public virtual Account Account1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
