//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oauth_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Cartings = new HashSet<Carting>();
        }
    
        public string PRODUCTNAME { get; set; }
        public string PROVIDER { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> COST { get; set; }
        public string IMAGE { get; set; }
        public string DIMENSION { get; set; }
    
        public virtual ICollection<Carting> Cartings { get; set; }
    }
}
